#!/usr/bin/env just --justfile
set positional-arguments

default: 
	just --list

serve:
	just b serve

build:
	mdbook build

alias b := book
@book cmd:
	mdbook $1

open:
	xdg-open content/book/html/index.html

push:
	just build && scp -r book/html webedit@lesnake.xyz:/var/www
